[package]
name = "react-wasm-table-core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[features]
debug-log = []

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
taffy = "0.9"
